---
title: "Determinantes"
format: revealjs
---

El determinante para una matriz cuadrada $2\times 2$ es:

$$ det(A) = \begin{vmatrix} a & b  \\ c & d \end{vmatrix} = ad-bc $$

Para una matriz cuadrada $3\times 3$ es:

$$ det(A) = \begin{vmatrix} a & b & c \\ d & e & f \\ g & h & i \\ \color{red}{a} & \color{red}{b} & \color{red}{c} \\\color{red}{d}&\color{red}{e}&\color{red}{f}\end{vmatrix} = aei+bfg+cdh-ceg-bdi-afh $$

---

De forma general el determinante de una matriz cuadrada $n\times n$ es:

$$ det(A) = \begin{vmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{n1} & a_{n2} & \cdots & a_{nn} \end{vmatrix} = \sum_{\sigma} (-1)^{\sigma} a_{1\sigma(1)}a_{2\sigma(2)}\cdots a_{n\sigma(n)} $$

---

Las propiedades de los determinantes son las siguientes:

1. Si una fila o columna de un determinante es nula, entonces el determinante es nulo.
2. Si intercambio dos filas o dos columnas de un determinante, el determinante cambia de signo.
3. $det(\alpha A)=\alpha^n det(A)$.
4. $det(A^T) = det(A)$.
5. $det(A \cdot B) = det(A) \cdot det(B)$.

---

6. $\begin{vmatrix} a & b  \\ c+f & d+g \end{vmatrix} =\begin{vmatrix} a & b  \\ c & d \end{vmatrix}+\begin{vmatrix} a & b  \\ f & g \end{vmatrix}$.
7. $det(AB)=det(A)det(B)$.

---

Note que si multiplico un fila por un escalar y la sumo a otra fila el determinante no cambia.


- Si $A$ es una matriz triangular superior, ¿Cuál es el determinante de $A$?

---

## Desarrollo por cofactores

Para calcular el determinante de una matriz $A$ de $n\times n$ se puede hacer por cofactores.

1. Se elige una fila o columna de la matriz.
2. Se calcula el determinante de la matriz que queda al eliminar la fila y columna seleccionada.
3. Se multiplica el determinante por el elemento de la fila o columna seleccionada y se multiplica por 
$(-1)^{i+j}$ donde $i$ y $j$ son los índices de la fila y columna seleccionada.

---

Por ejemplo, para la matriz $A$ de $3\times 3$:
$$|A|=\begin{vmatrix}
3&-1&2\\
4&5&6\\
7&1&2
\end{vmatrix}$$


Así los menores son:
$$M_{11}=\begin{vmatrix}
5&6\\
1&2
\end{vmatrix},\quad M_{12}=\begin{vmatrix}
4&6\\
7&2
\end{vmatrix},\quad M_{13}=\begin{vmatrix}
4&5\\
7&1
\end{vmatrix}$$


Y el determinante es:

$$|A|=\color{red}{(-1)^{1+1}}3\cdot M_{11}+\color{red}{(-1)^{1+2}}(-1)\cdot 4\cdot M_{12}+\color{red}{(-1)^{1+3}}2\cdot M_{13}$$


---

## inversa de una matriz 


La inversa de una matriz $A$ es una matriz $A^{-1}$ tal que:

$$A\cdot A^{-1} = A^{-1}\cdot A = I$$

Donde $I$ es la matriz identidad.

Se puede calcular con la fórmula:

$$A^{-1} = \frac{1}{det(A)}\cdot adj(A)$$

Donde $adj(A)$ es la matriz adjunta de $A$.

---

La matriz adjunta de $A$ se calcula de la siguiente forma:

1. Se calcula la matriz de cofactores

---

## regla de Cramer

La regla de Cramer es un método para resolver sistemas de ecuaciones lineales.

Si tengo un sistema de ecuaciones lineales de la forma:

$$\begin{align*}
a_{11}x_1+a_{12}x_2+\cdots+a_{1n}x_n&=b_1\\
a_{21}x_1+a_{22}x_2+\cdots+a_{2n}x_n&=b_2\\
\vdots\\
a_{n1}x_1+a_{n2}x_2+\cdots+a_{nn}x_n&=b_n
\end{align*}$$

---

La solución del sistema es:
$$x_1=\frac{det(A_1)}{det(A)},\quad x_2=\frac{det(A_2)}{det(A)},\quad\cdots,\quad x_n=\frac{det(A_n)}{det(A)}$$

Donde $A$ es la matriz de coeficientes del sistema y $A_i$ es la matriz que se obtiene al reemplazar la columna $i$ de $A$ por el vector de términos independientes.

---


